import type { Metadata } from "next";

import { SideNav } from "~/components/side-nav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
} satisfies Metadata;

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className='container mx-auto pt-12'>
      <div className='flex gap-8'>
        <SideNav />
        <div className='w-full'>{children}</div>
      </div>
    </main>
  );
}
